<?php

namespace HuaweiCloud\SDK\SecMaster\V2\Model;
use HuaweiCloud\SDK\Core\Utils\ObjectSerializer;
use HuaweiCloud\SDK\Core\Utils\ModelInterface;
use HuaweiCloud\SDK\Core\SdkResponse;

        class IsapTableProcessError
{
    /**
     * Possible values of this enum
     */
    const NONE = 'NONE';
    const MISSING_ASSOCIATIONS = 'MISSING_ASSOCIATIONS';
    const FAILED_INIT_STORAGE_RESOURCES_WHEN_CREATING = 'FAILED_INIT_STORAGE_RESOURCES_WHEN_CREATING';
    const FAILED_INIT_FLINK_RESOURCES_WHEN_CREATING = 'FAILED_INIT_FLINK_RESOURCES_WHEN_CREATING';
    const FAILED_DELETE_FLINK_RESOURCES_WHEN_DELETING = 'FAILED_DELETE_FLINK_RESOURCES_WHEN_DELETING';
    const FAILED_DELETE_STORAGE_RESOURCES_WHEN_DELETING = 'FAILED_DELETE_STORAGE_RESOURCES_WHEN_DELETING';
    const FAILED_DELETE_ALL_RESOURCES_WHEN_DELETING = 'FAILED_DELETE_ALL_RESOURCES_WHEN_DELETING';
    const FAILED_UPDATE_STORAGE_SETTING = 'FAILED_UPDATE_STORAGE_SETTING';
    const FAILED_UPDATE_FLINK_SCHEMA = 'FAILED_UPDATE_FLINK_SCHEMA';
    const FAILED_UPDATE_STORAGE_SCHEMA = 'FAILED_UPDATE_STORAGE_SCHEMA';
    const FAILED_TO_APPLY_RESOURCE = 'FAILED_TO_APPLY_RESOURCE';
    const FAILED_TO_UPGRADE_RESOURCE_MODEL = 'FAILED_TO_UPGRADE_RESOURCE_MODEL';
    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::NONE,
            self::MISSING_ASSOCIATIONS,
            self::FAILED_INIT_STORAGE_RESOURCES_WHEN_CREATING,
            self::FAILED_INIT_FLINK_RESOURCES_WHEN_CREATING,
            self::FAILED_DELETE_FLINK_RESOURCES_WHEN_DELETING,
            self::FAILED_DELETE_STORAGE_RESOURCES_WHEN_DELETING,
            self::FAILED_DELETE_ALL_RESOURCES_WHEN_DELETING,
            self::FAILED_UPDATE_STORAGE_SETTING,
            self::FAILED_UPDATE_FLINK_SCHEMA,
            self::FAILED_UPDATE_STORAGE_SCHEMA,
            self::FAILED_TO_APPLY_RESOURCE,
            self::FAILED_TO_UPGRADE_RESOURCE_MODEL,
        ];
    }
}

